[package]
name = "ttvy"
authors = ["tsorak"]
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttvy_core = { path = "../ttvy_core" }
tokio = { version = "^1.36.0", features = ["full"] }
hex_color = "^3.0.0"
clap = { version = "4.5.9", features = ["derive", "cargo"] }
ratatui = "0.29"
crossterm = { version = "0.28", features = ["event-stream"] }
futures = "0.3"
